pub mod bridge;

unsafe extern "C" {
    // Qt plugin entry point generated by cxx-qt-build. Declaring it here forces
    // the linker to pull qt_plugin_instance from the generated C++ archive into
    // the cdylib (it's otherwise dropped as unreferenced dead code).
    fn qt_plugin_instance() -> *mut ::std::ffi::c_void;
}

#[used]
#[unsafe(no_mangle)]
static _QT_PLUGIN_INSTANCE: unsafe extern "C" fn() -> *mut ::std::ffi::c_void = qt_plugin_instance;
